### ISSUE TITLE
package.json exports

### ISSUE THREAD

**Issue by T00rk** [aldy505/generate-passphrase#20]
I have this error while compiling my project which is using `generate-passphrase`.
```
There are types at '/node_modules/generate-passphrase/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". 
The 'generate-passphrase' library may need to update its package.json or typings.
```

It works when I edit `generate-passphrase` package.json like this:
(add types: index.d.ts)
```
exports": 
{
  ".":
  {
    "import": "./dist/index.mjs",
    "require": "./dist/index.cjs",
    "types: "./dist/index.d.ts"
  },
  "./package.json": "./package.json",
  "./*": "./*"
},
```

**Comment by aldy505** [comment]
Hi. I was surprised that there is someone who uses my old library. I'll update everything within this weekend (so expect in 2 days).

**Comment by aldy505** [comment]
Sorry for the delay, I'll be working on this tomorrow morning (on my time -- so it's 1 AM UTC)

**Comment by aldy505** [comment]
It's released now https://github.com/aldy505/generate-passphrase/releases/tag/v1.3.0
